# Generated by sdk/schema/types.py; edit the Rust contracts.
from __future__ import annotations
from typing import Any, Literal, Required, TypedDict

class AnswerPack(TypedDict, total=False):
    armCoverage: Required[list[ArmCoverage]]
    browseHits: Required[list[BrowseHit]]
    claims: list[Claim]
    grepHits: list[GrepHit]
    headSeq: Required[int]
    matchedNodes: Required[list[ClassNode]]
    node: PackNode | None
    notes: Required[list[UserNote]]
    promptHits: Required[list[PackPromptHit]]
    query: str | None
    retrieval: RetrievalReport
    sharedHits: list[ForeignHit]
    truncated: Required[list[str]]

Arm = Literal['Node', 'Note', 'Lexical', 'Grep', 'Semantic', 'Shared', 'Claim', 'Neighbor']
class ArmCoverage(TypedDict, total=False):
    absentBecause: str | None
    arm: Required[Arm]
    hits: Required[int]
    ran: Required[bool]

class ArmHit(TypedDict, total=False):
    arm: Required[Arm]
    rank: Required[int]
    score: Required[float]

class BrowseHit(TypedDict, total=False):
    caption: str | None
    id: Required[int]
    score: Required[float]
    seq: int | None
    shotKey: str | None
    snippet: Required[str]
    stage: Required[str]
    title: str | None
    ts: Required[int]
    url: Required[str]

class Claim(TypedDict, total=False):
    contradicts: list[str]
    derivation: Required[ClaimDerivation]
    eventSeq: Required[int]
    id: Required[str]
    modelVersion: str | None
    organizerRun: int | None
    predicate: Required[ClaimPredicate]
    recordedAt: Required[int]
    scope: Required[Scope]
    sources: Required[list[ClaimSource]]
    subject: Required[str]
    supersedes: list[str]
    unresolvedAlternatives: Required[list[str]]
    validFrom: Required[int]
    validUntil: int | None
    value: Required[ClaimValue]

ClaimDerivation = Literal['structured', 'gardener']
ClaimPredicate = Literal['preference', 'project_configuration', 'selected_technology', 'constraint', 'decision', 'relationship']
class ClaimQuery(TypedDict, total=False):
    evidenceFilter: EvidenceFilter
    knownAt: int | None
    limit: int | None
    predicate: ClaimPredicate | None
    q: str | None
    scope: Scope
    subject: str | None
    validAt: int | None

ClaimRole = Literal['user', 'assistant', 'agent', 'system', 'tool']
class ClaimSource(TypedDict, total=False):
    chainId: Required[str]
    quote: Required[str]
    role: Required[ClaimRole]
    seq: Required[int]
    startByte: int | None

class ClaimValue0(TypedDict):
    type: Literal['text']
    value: str

class ClaimValue1(TypedDict):
    type: Literal['boolean']
    value: bool

class ClaimValue2(TypedDict):
    type: Literal['number']
    value: float

ClaimValue = ClaimValue0 | ClaimValue1 | ClaimValue2
class ClaimWrite(TypedDict, total=False):
    contradicts: list[str]
    derivation: Required[ClaimDerivation]
    id: Required[str]
    modelVersion: str | None
    organizerRun: int | None
    predicate: Required[ClaimPredicate]
    scope: Required[Scope]
    sources: Required[list[ClaimSource]]
    subject: Required[str]
    supersedes: list[str]
    validFrom: Required[int]
    validUntil: int | None
    value: Required[ClaimValue]

class ClassLink(TypedDict, total=False):
    createdAt: Required[int]
    id: Required[int]
    nodeId: Required[str]
    note: str | None
    status: Required[str]
    targetId: Required[str]
    targetKind: Required[str]

class ClassNode(TypedDict, total=False):
    createdAt: Required[int]
    curatedBy: str | None
    id: Required[str]
    ipName: str | None
    kind: Required[str]
    parentId: str | None
    pinned: Required[bool]
    projectPath: str | None
    status: Required[str]
    summary: str | None
    title: Required[str]
    updatedAt: Required[int]

class ClassObservation(TypedDict, total=False):
    citeSeqs: Required[list[int]]
    createdAt: Required[int]
    createdSeq: int | None
    dismissed: Required[bool]
    id: Required[int]
    nodeId: Required[str]
    pinned: Required[bool]
    retiredAt: int | None
    retiredReason: str | None
    summary: Required[str]

class ContextBlock(TypedDict, total=False):
    coverage: list[ArmCoverage]
    retrieval: RetrievalReport
    terms: Required[list[str]]
    text: str | None
    truncated: list[str]

class ContextRequest(TypedDict, total=False):
    filter: EvidenceFilter
    maxBytes: int | None
    maxTokens: int | None
    node: str | None
    q: str
    scope: Scope
    traceId: str | None

class DecisionRequest(TypedDict, total=False):
    kind: str | None
    scope: Scope
    sourceSeq: int

class EvidenceFilter(TypedDict, total=False):
    after: int | None
    before: int | None
    knownAt: int | None
    roles: list[str]
    validAt: int | None

class EvidenceRecord(TypedDict, total=False):
    chainId: Required[str]
    item: LakeItem | None
    seq: Required[int]
    status: Required[str]

class EvidenceRequest(TypedDict, total=False):
    chainId: str | None
    scope: Scope
    seq: int

class ForeignHit(TypedDict, total=False):
    arms: Required[list[ArmHit]]
    chainId: Required[str]
    project: str | None
    redaction: Required[str]
    role: Required[str]
    score: Required[float]
    seq: Required[int]
    source: Required[str]
    text: str | None

class ForgetReceipt(TypedDict, total=False):
    forgotten: Required[bool]
    seq: int | None

class ForgetRequest(TypedDict, total=False):
    confirm: str
    scope: Scope
    targetId: str
    targetKind: str

class GrepHit(TypedDict, total=False):
    excerpt: Required[str]
    kind: Required[str]
    label: Required[str]
    seq: int | None
    ts: Required[int]

class IndexReadiness(TypedDict, total=False):
    eligibleSources: int
    indexedSources: int
    model: str | None
    pendingSources: int

class IngestItem(TypedDict, total=False):
    body: str
    project: str | None
    role: str | None
    run: str | None
    session: str | None
    ts: int | None

class IngestReceipt(TypedDict, total=False):
    recorded: Required[list[int]]
    skipped: Required[int]

class IngestRequest(TypedDict, total=False):
    items: list[IngestItem]
    scope: Scope

class LakeItem(TypedDict, total=False):
    body: str | None
    kind: Required[str]
    missionId: str | None
    model: str | None
    origin: str | None
    parentSessionId: str | None
    projectPath: str | None
    refId: str | None
    refKind: str | None
    role: str | None
    seq: Required[int]
    sessionId: str | None
    surface: str | None
    threadId: str | None
    threadKind: str | None
    ts: Required[int]

class PackLink(TypedDict, total=False):
    createdAt: Required[int]
    id: Required[int]
    label: str | None
    nodeId: Required[str]
    note: str | None
    status: Required[str]
    supersededBy: int | None
    targetId: Required[str]
    targetKind: Required[str]

class PackNode(TypedDict, total=False):
    children: Required[list[ClassNode]]
    grandchildren: Required[list[ClassNode]]
    links: Required[list[PackLink]]
    node: Required[ClassNode]
    observations: Required[list[ClassObservation]]

class PackPromptHit(TypedDict, total=False):
    arms: list[ArmHit]
    body: str | None
    duplicateOf: list[int]
    kind: Required[str]
    missionId: str | None
    model: str | None
    origin: str | None
    parentSessionId: str | None
    projectPath: str | None
    refId: str | None
    refKind: str | None
    role: str | None
    seq: Required[int]
    sessionId: str | None
    stage: Required[str]
    supersededBy: int | None
    surface: str | None
    threadId: str | None
    threadKind: str | None
    ts: Required[int]

class RememberRequest(TypedDict, total=False):
    asUser: bool
    project: str | None
    scope: Scope
    text: str

class RetrievalReport(TypedDict, total=False):
    candidateLimit: int
    candidatesConsidered: int
    candidatesReturned: int
    continuation: str | None
    errors: list[str]
    index: IndexReadiness
    snapshotHash: str
    timingsUs: dict[str, int]
    traceId: str | None
    version: str

class RetrievalTrace(TypedDict, total=False):
    config: Any
    coverage: Any
    cuts: list[str]
    elapsedMs: float
    errors: list[str]
    headSeq: int
    id: str
    replay: str
    scope: Scope
    selectedSeqs: list[int]
    snapshotHash: str
    startedAt: int

class Scope(TypedDict, total=False):
    agent: str | None
    includeShared: bool
    org: str | None
    principal: str | None
    project: str | None
    run: str | None

class SearchRequest(TypedDict, total=False):
    candidateLimit: int | None
    cursor: str | None
    filter: EvidenceFilter
    limit: int | None
    maxTokens: int | None
    node: str | None
    q: str | None
    scope: Scope
    traceId: str | None

class TraceRequest(TypedDict, total=False):
    id: str | None
    limit: int | None
    scope: Scope

class UserNote(TypedDict, total=False):
    createdAt: Required[int]
    id: Required[int]
    seq: int | None
    starred: Required[bool]
    targetId: str | None
    targetKind: Required[str]
    text: Required[str]
    updatedAt: Required[int]

class WriteReceipt(TypedDict, total=False):
    id: int | None
    seq: int | None
