#!/usr/bin/env python3
"""Generate SDK types from the generated schema; no SDK field lists to drift."""
import argparse
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[2]


def render(schema):
    def ts(s):
        if "$ref" in s: return s["$ref"].rsplit("/", 1)[1]
        if "const" in s: return json.dumps(s["const"])
        if "oneOf" in s: return " | ".join(ts(x) for x in s["oneOf"])
        if "additionalProperties" in s: return f"Record<string, {ts(s['additionalProperties'])}>"
        if s.get("type") == "object": return "{" + "; ".join(f"{k}: {ts(v)}" for k, v in s["properties"].items()) + "}"
        if "enum" in s: return " | ".join(json.dumps(v) for v in s["enum"])
        if "anyOf" in s: return " | ".join(ts(x) for x in s["anyOf"])
        if s.get("type") == "array": return f"Array<{ts(s['items'])}>"
        return {"string": "string", "integer": "number", "number": "number", "boolean": "boolean", "null": "null"}.get(s.get("type"), "unknown")
    def py(s):
        if "$ref" in s: return s["$ref"].rsplit("/", 1)[1]
        if "additionalProperties" in s: return f"dict[str, {py(s['additionalProperties'])}]"
        if "const" in s: return "Literal[" + repr(s["const"]) + "]"
        if "oneOf" in s: return " | ".join("ClaimValue" + str(i) for i in range(len(s["oneOf"])))
        if "enum" in s: return "Literal[" + ", ".join(repr(v) for v in s["enum"]) + "]"
        if "anyOf" in s: return " | ".join(py(x) for x in s["anyOf"])
        if s.get("type") == "array": return f"list[{py(s['items'])}]"
        return {"string": "str", "integer": "int", "number": "float", "boolean": "bool", "null": "None"}.get(s.get("type"), "Any")
    typescript = ["// Generated by sdk/schema/types.py; edit the Rust contracts."]
    python = ["# Generated by sdk/schema/types.py; edit the Rust contracts.", "from __future__ import annotations", "from typing import Any, Literal, Required, TypedDict", ""]
    for name, definition in schema["$defs"].items():
        if "oneOf" in definition:
            for index, variant in enumerate(definition["oneOf"]):
                python.append(f"class {name}{index}(TypedDict):")
                python.extend(f"    {key}: {py(field)}" for key, field in variant["properties"].items())
                python.append("")
        if definition.get("type") == "object":
            typescript.append(f"export interface {name} {{")
            python.append(f"class {name}(TypedDict, total=False):")
            for key, field in definition["properties"].items():
                required = key in definition.get("required", [])
                typescript.append(f"  {key}{'' if required else '?'}: {ts(field)};")
                python.append(f"    {key}: {'Required[' + py(field) + ']' if required else py(field)}")
            if not definition["properties"]: python.append("    pass")
            typescript.append("}")
            python.append("")
        else:
            typescript.append(f"export type {name} = {ts(definition)};")
            python.append(f"{name} = {py(definition)}")
    return "\n".join(typescript) + "\n", "\n".join(python).rstrip("\n") + "\n"


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    schema = json.loads((ROOT / "sdk/schema/api-v1.schema.json").read_text())
    ts, py = render(schema)
    for path, text in [(ROOT / "sdk/typescript/src/generated.d.ts", ts), (ROOT / "sdk/python/polis_memory/generated.py", py)]:
        if args.check:
            if not path.exists() or path.read_text() != text: raise SystemExit(f"stale generated SDK types: {path}")
        else: path.write_text(text)
