// Generated by sdk/schema/types.py; edit the Rust contracts.
export interface AnswerPack {
  armCoverage: Array<ArmCoverage>;
  browseHits: Array<BrowseHit>;
  claims?: Array<Claim>;
  grepHits?: Array<GrepHit>;
  headSeq: number;
  matchedNodes: Array<ClassNode>;
  node?: PackNode | null;
  notes: Array<UserNote>;
  promptHits: Array<PackPromptHit>;
  query?: string | null;
  retrieval?: RetrievalReport;
  sharedHits?: Array<ForeignHit>;
  truncated: Array<string>;
}
export type Arm = "Node" | "Note" | "Lexical" | "Grep" | "Semantic" | "Shared" | "Claim" | "Neighbor";
export interface ArmCoverage {
  absentBecause?: string | null;
  arm: Arm;
  hits: number;
  ran: boolean;
}
export interface ArmHit {
  arm: Arm;
  rank: number;
  score: number;
}
export interface BrowseHit {
  caption?: string | null;
  id: number;
  score: number;
  seq?: number | null;
  shotKey?: string | null;
  snippet: string;
  stage: string;
  title?: string | null;
  ts: number;
  url: string;
}
export interface Claim {
  contradicts?: Array<string>;
  derivation: ClaimDerivation;
  eventSeq: number;
  id: string;
  modelVersion?: string | null;
  organizerRun?: number | null;
  predicate: ClaimPredicate;
  recordedAt: number;
  scope: Scope;
  sources: Array<ClaimSource>;
  subject: string;
  supersedes?: Array<string>;
  unresolvedAlternatives: Array<string>;
  validFrom: number;
  validUntil?: number | null;
  value: ClaimValue;
}
export type ClaimDerivation = "structured" | "gardener";
export type ClaimPredicate = "preference" | "project_configuration" | "selected_technology" | "constraint" | "decision" | "relationship";
export interface ClaimQuery {
  evidenceFilter?: EvidenceFilter;
  knownAt?: number | null;
  limit?: number | null;
  predicate?: ClaimPredicate | null;
  q?: string | null;
  scope?: Scope;
  subject?: string | null;
  validAt?: number | null;
}
export type ClaimRole = "user" | "assistant" | "agent" | "system" | "tool";
export interface ClaimSource {
  chainId: string;
  quote: string;
  role: ClaimRole;
  seq: number;
  startByte?: number | null;
}
export type ClaimValue = {type: "text"; value: string} | {type: "boolean"; value: boolean} | {type: "number"; value: number};
export interface ClaimWrite {
  contradicts?: Array<string>;
  derivation: ClaimDerivation;
  id: string;
  modelVersion?: string | null;
  organizerRun?: number | null;
  predicate: ClaimPredicate;
  scope: Scope;
  sources: Array<ClaimSource>;
  subject: string;
  supersedes?: Array<string>;
  validFrom: number;
  validUntil?: number | null;
  value: ClaimValue;
}
export interface ClassLink {
  createdAt: number;
  id: number;
  nodeId: string;
  note?: string | null;
  status: string;
  targetId: string;
  targetKind: string;
}
export interface ClassNode {
  createdAt: number;
  curatedBy?: string | null;
  id: string;
  ipName?: string | null;
  kind: string;
  parentId?: string | null;
  pinned: boolean;
  projectPath?: string | null;
  status: string;
  summary?: string | null;
  title: string;
  updatedAt: number;
}
export interface ClassObservation {
  citeSeqs: Array<number>;
  createdAt: number;
  createdSeq?: number | null;
  dismissed: boolean;
  id: number;
  nodeId: string;
  pinned: boolean;
  retiredAt?: number | null;
  retiredReason?: string | null;
  summary: string;
}
export interface ContextBlock {
  coverage?: Array<ArmCoverage>;
  retrieval?: RetrievalReport;
  terms: Array<string>;
  text?: string | null;
  truncated?: Array<string>;
}
export interface ContextRequest {
  filter?: EvidenceFilter;
  maxBytes?: number | null;
  maxTokens?: number | null;
  node?: string | null;
  q?: string;
  scope?: Scope;
  traceId?: string | null;
}
export interface DecisionRequest {
  kind?: string | null;
  scope?: Scope;
  sourceSeq?: number;
}
export interface EvidenceFilter {
  after?: number | null;
  before?: number | null;
  knownAt?: number | null;
  roles?: Array<string>;
  validAt?: number | null;
}
export interface EvidenceRecord {
  chainId: string;
  item?: LakeItem | null;
  seq: number;
  status: string;
}
export interface EvidenceRequest {
  chainId?: string | null;
  scope?: Scope;
  seq?: number;
}
export interface ForeignHit {
  arms: Array<ArmHit>;
  chainId: string;
  project?: string | null;
  redaction: string;
  role: string;
  score: number;
  seq: number;
  source: string;
  text?: string | null;
}
export interface ForgetReceipt {
  forgotten: boolean;
  seq?: number | null;
}
export interface ForgetRequest {
  confirm?: string;
  scope?: Scope;
  targetId?: string;
  targetKind?: string;
}
export interface GrepHit {
  excerpt: string;
  kind: string;
  label: string;
  seq?: number | null;
  ts: number;
}
export interface IndexReadiness {
  eligibleSources?: number;
  indexedSources?: number;
  model?: string | null;
  pendingSources?: number;
}
export interface IngestItem {
  body?: string;
  project?: string | null;
  role?: string | null;
  run?: string | null;
  session?: string | null;
  ts?: number | null;
}
export interface IngestReceipt {
  recorded: Array<number>;
  skipped: number;
}
export interface IngestRequest {
  items?: Array<IngestItem>;
  scope?: Scope;
}
export interface LakeItem {
  body?: string | null;
  kind: string;
  missionId?: string | null;
  model?: string | null;
  origin?: string | null;
  parentSessionId?: string | null;
  projectPath?: string | null;
  refId?: string | null;
  refKind?: string | null;
  role?: string | null;
  seq: number;
  sessionId?: string | null;
  surface?: string | null;
  threadId?: string | null;
  threadKind?: string | null;
  ts: number;
}
export interface PackLink {
  createdAt: number;
  id: number;
  label?: string | null;
  nodeId: string;
  note?: string | null;
  status: string;
  supersededBy?: number | null;
  targetId: string;
  targetKind: string;
}
export interface PackNode {
  children: Array<ClassNode>;
  grandchildren: Array<ClassNode>;
  links: Array<PackLink>;
  node: ClassNode;
  observations: Array<ClassObservation>;
}
export interface PackPromptHit {
  arms?: Array<ArmHit>;
  body?: string | null;
  duplicateOf?: Array<number>;
  kind: string;
  missionId?: string | null;
  model?: string | null;
  origin?: string | null;
  parentSessionId?: string | null;
  projectPath?: string | null;
  refId?: string | null;
  refKind?: string | null;
  role?: string | null;
  seq: number;
  sessionId?: string | null;
  stage: string;
  supersededBy?: number | null;
  surface?: string | null;
  threadId?: string | null;
  threadKind?: string | null;
  ts: number;
}
export interface RememberRequest {
  asUser?: boolean;
  project?: string | null;
  scope?: Scope;
  text?: string;
}
export interface RetrievalReport {
  candidateLimit?: number;
  candidatesConsidered?: number;
  candidatesReturned?: number;
  continuation?: string | null;
  errors?: Array<string>;
  index?: IndexReadiness;
  snapshotHash?: string;
  timingsUs?: Record<string, number>;
  traceId?: string | null;
  version?: string;
}
export interface RetrievalTrace {
  config?: unknown;
  coverage?: unknown;
  cuts?: Array<string>;
  elapsedMs?: number;
  errors?: Array<string>;
  headSeq?: number;
  id?: string;
  replay?: string;
  scope?: Scope;
  selectedSeqs?: Array<number>;
  snapshotHash?: string;
  startedAt?: number;
}
export interface Scope {
  agent?: string | null;
  includeShared?: boolean;
  org?: string | null;
  principal?: string | null;
  project?: string | null;
  run?: string | null;
}
export interface SearchRequest {
  candidateLimit?: number | null;
  cursor?: string | null;
  filter?: EvidenceFilter;
  limit?: number | null;
  maxTokens?: number | null;
  node?: string | null;
  q?: string | null;
  scope?: Scope;
  traceId?: string | null;
}
export interface TraceRequest {
  id?: string | null;
  limit?: number | null;
  scope?: Scope;
}
export interface UserNote {
  createdAt: number;
  id: number;
  seq?: number | null;
  starred: boolean;
  targetId?: string | null;
  targetKind: string;
  text: string;
  updatedAt: number;
}
export interface WriteReceipt {
  id?: number | null;
  seq?: number | null;
}
